#! /bin/sh
$HOME/.scripts/multimonitor.sh
nitrogen --restore &
picom --experimental-backend &
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP1 -d 1 2 3 4 5
bspc monitor HDMI1 -d 1 2 3 4 5

bspc monitor eDP1 -s HDMI1

bspc config border_width         2
bspc config window_gap           2
bspc config top_paddig          30

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true